### ISSUE TITLE
fix: respect proto

### ISSUE THREAD

**Issue by andrewvasilchuk** [danielroe/nuxt-typed-vuex#101]
**🐛 The bug**
When `state` is an instance of a class, prototype chain is lost.

**🛠️ To reproduce**

```ts
import Vue from 'vue'
import Vuex from 'vuex'

import { useAccessor } from 'typed-vuex'

class Car {
  constructor(public name: string) {}

  setName(value: string) {
    this.name = value
  }
}

const state = new Car('BMW')

const mutations = mutationTree(state, {
  mutation(state, name: string) {
    state.setName(name) // OK
  },
})

const storePattern = {
  state,
  mutations,
}

const store = new Vuex.Store(storePattern)

export const accessor = useAccessor(store, storePattern)

accessor.setName('name') // Error, prototype chain is lost
```

**🌈 Expected behaviour**
Prototype chain is preserved.

**ℹ️ Additional context**
Consider using [`Object.create`](https://developer.mozilla.org/ru/docs/Web/JavaScript/Reference/Global_Objects/Object/create) [here](https://github.com/danielroe/nuxt-typed-vuex/blob/master/packages/typed-vuex/src/accessor.ts#L38).

**Comment by danielroe** [comment]
I really appreciate these bug reports - thanks @andrewvasilchuk.

On this occasion it looks like Vuex isn't meant to be used with classes in state - see https://vuex.vuejs.org/guide/state.html#single-state-tree.

Discussion welcome, however.

**Comment by andrewvasilchuk** [comment]
Yes, but the accessor behaves like a transparent proxy/decorator, so to be even more transparent it should preserve prototype chain.
