### ISSUE TITLE
feat: allow root mutations/actions from module store

### ISSUE THREAD

**Issue by Yolley** [danielroe/nuxt-typed-vuex#116]
**🐛 The bug**
In vuex store there is a way to use root mutations/actions from module
https://vuex.vuejs.org/api/#commit

With nuxt-typed-vuex, as I understand, there is no such type in tree, so, when I pass this option and try to run my project, I get an error like

`88:16 Argument of type '"rootMutation"' is not assignable to parameter of type '"actionDoSomething"'.`

**🛠️ To reproduce**
1. Add some mutations to root state
```typescript
// index.ts
export const mutations = mutationTree(state, {
  rootMutation: (state: RootState) => {
    // mutate something
  },
});
```
2. Try to use root mutation from module with `{ root: true }` option like
```typescript
// module.ts
export const actions = actionTree(
  { state, getters, mutations },
  {
    actionDoSomething({ commit }) {
      commit('rootMutation', null, { root: true });
    },
}
```
3. Try to run the project
4. Get an error in log

**🌈 Expected behaviour**
No errors

**Comment by danielroe** [comment]
@Yolley The reason I've not enabled that is because it would stop the type inference working for local commits. There is a type-safe way of making root mutations, however. Try:
```ts
// module.ts
export const actions = actionTree(
  { state, getters, mutations },
  {
    actionDoSomething() {
      this.app.$accessor.rootMutation()
    },
}
```

Does that work for you, or does your use case require calling `commit`?

**Comment by Yolley** [comment]
> @Yolley The reason I've not enabled that is because it would stop the type inference working for local commits (see [docs](https://nuxt-typed-vuex.roe.dev/store/actions.html)). There is a type-safe way of making root mutations, however. Try:
> 
> ```ts
> // module.ts
> export const actions = actionTree(
>   { state, getters, mutations },
>   {
>     actionDoSomething() {
>       this.app.$accessor.rootMutation()
>     },
> }
> ```
> 
> Does that work for you, or does your use case require calling `commit`?

Yes, this way works, thank you!
