### ISSUE TITLE
[FEATURE] Add nuxt-typed-vuex on Context API

### ISSUE THREAD

**Issue by ram231** [danielroe/nuxt-typed-vuex#12]
There's no format for how I can create an Issue.

say. I want to use the `$accessor` in the asyncData.

```javascript
 async asyncData({$accessor}) {
    console.log($accessor) // output: undefined
 },
```

it turns out. when I tried to check the `context`. the **$accessor** is accessible in `context.app.$accessor`
```javascript

  async asyncData({app}) {
    console.log(app.$accessor) // Will list all registered store in Vuex
   //console.log(store.$accessor) // this will also work
  },
```

It does solved my problem when accessing `$accessor` from the asyncData, but I don't know how to put the $accessor to the Context API in the `index.d.ts` file(provided from your example).

**Comment by danielroe** [comment]
Hi @ram231 - thanks for getting in touch!

1. I'll add asyncData as an example in the docs - great spot! (It currently only mentions [middleware](https://nuxt-typed-vuex.danielcroe.com/accessor/accessor.html#middleware).)

2. When you [add these types to your `index.d.ts`](https://nuxt-typed-vuex.danielcroe.com/setup.html#creating-type-definitions) is the $accessor not typed in asyncData for you?
   ```ts
   @Component({
     asyncData({ route, app: { $accessor } }) {
       $accessor.test // this is typed for me
     },
   })
   ```

**Comment by ram231** [comment]
Thanks for clarifying that @danielroe.

I'll be doing that convention instead of
```javascript
// Vanilla Vue
async asyncData({$accessor}){
 await $accessor.fetch();
}
```

**Comment by danielroe** [comment]
@ram231 Again, thanks for your issue.

1. I've [added issue templates](https://github.com/danielroe/nuxt-typed-vuex/issues/new/choose) for use in future.
2. I've updated the docs (a1c03cc955215eba38f8327fdd258186ef907790) with info about `asyncData`.

Let me know if you think there's any other way to make things better.
