### ISSUE TITLE
docs: Improving state type with interface

### ISSUE THREAD

**Issue by webcoderkz** [danielroe/nuxt-typed-vuex#120]
Documentation link: https://nuxt-typed-vuex.danielcroe.com/store/state.html

Current example:

```
export const state = () => ({
  // AVOID: This results in emails being typed as never[]
  emails: [],

  // This is correct
  emails: [] as string[],
})
```

But we can make it even prettier with an interface:

```
interface IState {
  (): {
    emails: string[]
  }
}

export const state: IState = () => ({})
```

Or there is some issues with interface? I just used interfaces myself everywhere, instead of type casting with `as` syntax.

**Comment by danielroe** [comment]
I prefer the inline type definition in the docs at the moment, but your approach certainly works too 😊
