### ISSUE TITLE
feat: support dynamic modules

### ISSUE THREAD

**Issue by andrewvasilchuk** [danielroe/nuxt-typed-vuex#13]
Can you please provide example of usage with dynamic modules?

**Comment by danielroe** [comment]
@andrewvasilchuk Sure. Would you share an example of the kind of code/use you have for dynamic modules?

**Comment by andrewvasilchuk** [comment]
```js
import { Module } from 'vuex'
import { ModuleState } from './types'
import getters from './getters'
import mutations from './mutations'
import actions from './actions'

export const state: StreamState = {
  foo: 'bar'
}

const namespaced: boolean = true

const MyModule: Module<ModuleState, any> = {
  namespaced,
  state,
  getters,
  actions,
  mutations,
}

export default MyModule
```

**Comment by andrewvasilchuk** [comment]
@danielroe, should I use `MutationTree, ActionTree, GetterTree`?

**Comment by danielroe** [comment]
@andrewvasilchuk No, don't use them - they confuse TS inference. Could you share how you are instantiating the dynamic module?

**Comment by andrewvasilchuk** [comment]
@danielroe 

```js
import MyModule from `@/vuex/modules/my-module`

beforeCreate() {
  this.$store.registerModule('module', MyModule)
}
```

**Comment by danielroe** [comment]
Here's a stab:

```ts
import { useAccessor } from 'nuxt-typed-vuex'
import dynamicModule from './dyn'

...
  mounted() {
    this.$store.registerModule('myNamespace', dynamicModule, {
      preserveState: false,
    })
    const accessor = useAccessor(this.$store, {
      state: () => ({}),
      getters: {},
      actions: {},
      mutations: {},
      modules: { myNamespace: dynamicModule },
    })
    accessor.myState // works and is typed
  }
```

However, note that this is a bit cumbersome and I can make it a bit nicer.

**Comment by andrewvasilchuk** [comment]
@danielroe , thank you a lot. One more question :)
Can I somehow drop these lines?
```js
state: () => ({}),
getters: {},
actions: {},
mutations: {},
```

**Comment by danielroe** [comment]
@andrewvasilchuk I'll make sure you can in the next release - my apologies!

**Comment by andrewvasilchuk** [comment]
@danielroe , Wow. Looking forward to the next release? Will it be hard to implement?

**Comment by danielroe** [comment]
@andrewvasilchuk Released! Let me know if it works for you.

**Comment by danielroe** [comment]
@andrewvasilchuk Sure, let me have a look into that. 😀

**Comment by andrewvasilchuk** [comment]
@danielroe , Thanks again. I think it would be super feature if you can create type checking for specific module (e.g `useDynamicModule(store, dynamicModule)`) 👍

**Comment by andrewvasilchuk** [comment]
@danielroe , I  am getting the following error 😢 

```js
const MyModule = {
  namespaced,
  state,
  getters,
  actions,
  mutations,
}

export default MyModule

export const accessorType = getAccessorType(MyModule)
```

And on my page:

```js
export default class Page extends Vue {
  accessor: typeof accessorType | null = null

  mounted() {
    this.accessor = useAccessor(this.$store, {
      modules: { module },
    })
  }
}

```

It expects that my module must be under module namespace.

**Comment by andrewvasilchuk** [comment]
@danielroe , What do yo think about it?
```js
this.accessor = useAccessor(this.$store,module);
```

**Comment by andrewvasilchuk** [comment]
@danielroe 
```js
export const useAccessor = <
  T extends State,
  G extends GetterTree<StateType<T>, any>,
  M extends MutationTree<StateType<T>>,
  A extends ActionTree<StateType<T>, any>,
  S extends NuxtModules
>(
  store: Store<any>,
  input: Partial<NuxtStoreInput<T, G, M, A, S>>,
  namespace?: string <-- here
) => {
  const accessor = createAccessor(store, input, namespace) <-- and here
  
  Object.keys(input.modules || {}).forEach(namespace => {
    accessor[namespace] = createAccessor(
      store,
      (input.modules as any)[namespace],
      namespace
    )
  })

  const storeType = getAccessorType(input)

  return accessor as typeof storeType
}
```

Also it would be nice if you can handle nested modules also. For example iterate over `input.modules.modules.modules` and create appropriate namespace. What do you think about it?

**Comment by danielroe** [comment]
@andrewvasilchuk Sounds good, on both fronts. :+1: And I think allowing namespace argument will allow nesting of modules with a recursive function.

**Comment by andrewvasilchuk** [comment]
@danielroe , Maybe something like this in `createAccessor`?
```js
const namespacedPath = namespace ? `${namespace}/` : ''
const accessor: Record<string, any> = {}

if (accessor.modules) {
  Object.keys(accessor.modules).forEach(key => {
    accessor[key] = createAccessor(store, accessor.modules[key], namespacedPath + key)
  })
}
```

**Comment by andrewvasilchuk** [comment]
@danielroe , Maybe something like this in `createAccessor`?

```js
const namespacedPath = namespace ? `${namespace}/` : ''
const accessor: Record<string, any> = {}

if (modules) {
  Object.keys(modules).forEach(key => {
    accessor[key] = createAccessor(store, modules[key], namespacedPath + key)
  })
}
```

**Comment by danielroe** [comment]
@andrewvasilchuk Fancy testing it? `nuxt-typed-vuex@0.1.10-beta.0` - and it should work just as you suggested:
```ts
const accessor = useAccessor(store, module, 'module')
```

**Comment by padarom** [comment]
https://github.com/danielroe/nuxt-typed-vuex/issues/13#issuecomment-549086627
> However, note that this is a bit cumbersome and I can make it a bit nicer. I take it you wouldn't expect to access your dynamic module through the global $accessor, and perhaps a helper function might be better, e.g.:

@danielroe I am trying to use [vuex-easy-firestore](https://github.com/mesqueeb/vuex-easy-firestore). The way it works is that modules aren't directly added to the Vuex store, but to their plugin instead. The plugin modifies the module and then dynamically adds it.  
I can add it to the `accessorType` which gives me type inference for the global `$accessor`, but obviously the module isn't actually included in it.

I need to reference these dynamic modules in many components, so it makes sense for them to be included in the global `$accessor`, instead of just a newly created one.

Do you think there's an easy way to allow for both?

**Comment by danielroe** [comment]
@padarom Would it be a solution to inject these stores separately in a plugin, much as the typed-vuex accessor is injected, for example as $firestores?

Then you would type that object separately.

**Comment by padarom** [comment]
That would work but wouldn't be ideal as I'd have to constantly switch between two accessors based on the module that I need, which makes the Firestore plugin less transparent than intended.

I'll roll with it for now though. Would you mind a PR adding a switch to `useAccessor` to toggle on injection into the global `$accessor`?

**Comment by danielroe** [comment]
@padarom Absolutely! (And sorry for the delay in replying.)
