### ISSUE TITLE
jest Unexpected token 'export'

### ISSUE THREAD

**Issue by Linus-Boehm** [danielroe/nuxt-typed-vuex#133]
**🐛 The bug**
What isn't working? Describe what the bug is.
`ts-jest` is complaining about `jest Unexpected token 'export'` in the `lib/index.js` of the build package

Current `lib/index.js`:
```
export { getStoreType } from './types/store';
export { actionTree } from './types/actions';
export { getterTree } from './types/getters';
export { mutationTree } from './types/mutations';
export { useAccessor, getAccessorType, getAccessorFromStore } from './accessor';
```

**🛠️ To reproduce**

**🌈 Expected behaviour**
What did you expect to happen? Is there a section in the docs about this?

using this package with a default `vue/cli` generated package, babel and `ts-jest` should work flawlessly

**ℹ️ Additional context**

You can workaround this, by changing your `jest.config` to something like:

```
...
transformIgnorePatterns: [
    '/node_modules/(?!typed-vuex)'
  ],
...
```

I'm not sure quite why it isn't able to interpretate the exports, maybe it's just my jest/babel settings. Feel free to close this as `wont-fix`, if this is caused specific by my settings, but at least its documented then. Also happy when you can point me to a possible solution or what the problem here is, I would be more then happy to provide a PR.

Thanks for the efforts on this package @danielroe , really solves some pains with vuex!

**Comment by dewita97** [comment]
I have exactly the same issue, but with pm2 @danielroe :/

**Comment by danielroe** [comment]
@Linus-Boehm I'm really sorry for the long delay in addressing this issue. Hopefully things will be fixed for you with the latest release of the package: `v0.1.21`.
