### ISSUE TITLE
fix: actions and accessorType is untyped when using nuxtServerInit()

### ISSUE THREAD

**Issue by webcoderkz** [danielroe/nuxt-typed-vuex#134]
Here's the reproduction link: https://codesandbox.io/s/elated-ives-x1hzb?file=/store/index.ts

Take a look at /store/index.ts file:

![image](https://user-images.githubusercontent.com/5739191/87966951-dc413480-cadf-11ea-9b0e-ba5e176919e6.png)

When i'm trying to use `$accessor` inside `nuxtServerInit()` then i'm gettin error about `actions` and `accessorType` - "
implicitly has type 'any' because it does not have a type annotation and is referenced directly or indirectly in its own initializer."

Actually what i'm trying to achieve here, is to fetch data, then commit it:

```js
    async nuxtServerInit(_vuexContext, nuxtContext: Context) {
      const data = await nuxtContext.app.$api.calc.getOffers()
      const offers = data.bundles
      const services = data.services
      const selectedInternet = offers[0].selected
      nuxtContext.app.$accessor.calculator.setInternet(
        offers[0].availableBundles[selectedInternet]
      )
    },
```

Also what's the purpose of `_vuexContext` if we're using `$accessor`?

**Comment by danielroe** [comment]
Just make sure to type the return type of the action that uses the accessor. This works fine:
```ts
    async nuxtServerInit(_vuexContext, nuxtContext: Context): Promise<void> {
      console.log(nuxtContext.app.$accessor.fullEmail);
    }
```
