### ISSUE TITLE
docs: A sample code may cause circular dependencies

### ISSUE THREAD

**Issue by hanshou101** [danielroe/nuxt-typed-vuex#144]
**📚 Is your documentation request related to a problem? Please describe.**
【Other action】 import 【accessor】, and ths 【accessor】 may import 【Other action】 too .
This will produce hidden annoying circular dependencies

**🔍 Where should you find it?**
[Getting started (Vue) - Typed Vuex](https://nuxt-typed-vuex.roe.dev/getting-started-vue#usage-within-the-store)

**ℹ️ Additional context**
A plugin to detect it : [aackerman/circular-dependency-plugin: Detect circular dependencies in modules compiled with Webpack](https://github.com/aackerman/circular-dependency-plugin)

**Comment by danielroe** [comment]
@hanshou101 Thanks for reporting ❤️ Would you be able to create a reproduction on GitHub or CodeSandbox?

**Comment by hanshou101** [comment]
Hello sir, I created this minimal repo: [typed-vuex-demo](https://github.com/hanshou101/typed-vuex-demo.git) .

As you can see, the first commit is the initialization of the scaffolding . The second commit is the incremental code with circular dependencies.

It will have an impact in two places: 
1. The web page will be blank and an error will be reported. 
2. [circular-dependency-plugin] The dependency path is detected and an error is reported.

**Comment by danielroe** [comment]
Thanks! I will take a look soon.

**Comment by danielroe** [comment]
@hanshou101 This is actually the same underlying issue as #100, and it is fixed by defining your state with a factory function, e.g.:
```ts
const state = () => ({
  otherEmail: '',
});
```
I [updated the state documentation](1f959138cb573ad7d901fb46758bc00aa54eb5c7) but failed to update the getting started guide so will do that straight away :+1: 

Many thanks for reporting this issue!
