### ISSUE TITLE
Question: TS lint error when used with nuxt-ts

### ISSUE THREAD

**Issue by userquin** [danielroe/nuxt-typed-vuex#148]
Hi:

My store looks like this `store/index.ts`:
```javascript
export const state = () => ({
  version: DEFAULT_APP_VERSION as string,
  loggedIn: false,
  userId: null as number | null,
  userName: null as string | null,
  userIdentity: null as string | null,
  userRole: null as UserRole | null,
  userMunicipios: [] as string[],
  busy: false,
  lastRequestedPath: null as string | null
});

type RootState = ReturnType<typeof state>;

export const getters = getterTree(state, {
  getVersion: (state) => state.version,
  isLoggedIn: (state) => state.loggedIn,
  getUserId: (state) => state.userId,
  getUserName: (state) => state.userName,
  getUserIdentity: (state) => state.userIdentity,
  getUserRole: (state) => state.userRole,
  getUserMunicipios: (state) => state.userMunicipios,
  isBusy: (state) => state.busy,
  getLastRequestedPath: (state) => state.lastRequestedPath
});
...
...
export const accessorType = getAccessorType({
  state,
  getters,
  mutations,
  actions
});
```

I have the following on `index.d.ts`:
```javascript
import { accessorType } from "@/store";

declare module "vue/types/vue" {
  interface Vue {
    $accessor: typeof accessorType;
  }
}

declare module "@nuxt/types" {
  interface NuxtAppOptions {
    $accessor: typeof accessorType;
  }
}
```
On my component `layout/default.vue`:
```javascript
<script lang="ts">
import { defineComponent, computed, ref, reactive } from "@vue/composition-api";
export default defineComponent({
  name: "default",
  setup(_props, { root }) {
    const title = computed(() => root.$accessor.getVersion);
    const version = computed(() => root.$accessor.getVersion);
    const loggedIn = computed(() => root.$accessor.isLoggedIn);
    return {
      title,
      version ,
      loggedIn
    };
  }
});
```
![eslint-error-2](https://user-images.githubusercontent.com/6311119/90571205-998f7c80-e1b1-11ea-9097-a17317334612.png)

`yarn build` (`nuxt-ts build`) and `yarn dev` (`nuxt-ts`) works but my IDE (Intellij 2020.2) shows previous error, how can I remove the error, any idea?

`yarn --version`: `1.22.4` 
`node --version`: `v12.18.3`
`vue --version`: `@vue/cli 4.5.3`
`yarn list nuxt`: `nuxt@2.14.1` 
`yarn list @vue/composition-api`: `@vue/composition-api@1.0.0-beta.10`

**Comment by danielroe** [comment]
@userquin I typically see this error if there is a problem in a type declaration file (might not be `index.d.ts`) - such as attempting to augment an interface in a non-module file (i.e. without importing something else).

Alternatively, it might be something specific to Intellij that I won't be able to help with.

Could you provide a reproduction? That might help narrow down the issue.

**Comment by userquin** [comment]
@danielroe thx, last update of intellij just works (was reproducible on 2020.2 but not on 2020.2.1), so I think this was an issue on intellj

**Comment by danielroe** [comment]
@userquin Glad things are sorted!
