### ISSUE TITLE
docs: How can I access the root state from a submodule?

### ISSUE THREAD

**Issue by michael-ottink** [danielroe/nuxt-typed-vuex#168]
**📚 Is your documentation request related to a problem? Please describe.**
I would like to know how to access the state from a action in a submodule.

**🔍 Where should you find it?**
I would like to see it in the example here https://nuxt-typed-vuex.roe.dev/runtime

**Comment by danielroe** [comment]
@michael-ottink You can use the accessor from within an action like this:
```ts
export const actions = actionTree(
  { state, getters, mutations },
  {
    async accessingRootState(): Promise<void> {
      console.log(this.app.$accessor.aSampleRootStateProperty)
    },
  }
)
```

There's a little more info at https://nuxt-typed-vuex.roe.dev/actions#referencing-other-modules
