### ISSUE TITLE
docs: how do I use it without nuxt?

### ISSUE THREAD

**Issue by andrewvasilchuk** [danielroe/nuxt-typed-vuex#20]
As I understood, this library can be used without `Nuxt.js`(or not?). Because library exposes useful helpers like `getAccessorType`, `useAccessor`. So we can create accessors (just a simple proxy) wherever we want? It would be great to add some docs about usage in projects scaffolded with Vue CLI (etc.).

Maybe I am wrong and it can not be used without `Nuxt.js`? Can you correct me?

**Comment by danielroe** [comment]
@andrewvasilchuk You're right, it could be. :smiley: What key topics about usage with Vue CLI do you think the docs should cover?

**Comment by andrewvasilchuk** [comment]
@danielroe, How to create `accessor` for the `store` and where to store it? Is it good idea to store it under `Vue.prototype.$accessor`? How to provide it globally, or better just import it from somewhere like this `import { storeAccessor } from '@/store'`?

**Comment by andrewvasilchuk** [comment]
@danielroe , If people who are not using `Nuxt.js` can use this library, it can bring more people who want to contribute. In our СIS Vue.js community chat (in Telegram) everybody is looking for typed vuex sollution, and there are many dissatisfies about `vuex-modules-decorators` (because of decorators, useless overhead, and bad code).

**Comment by andrewvasilchuk** [comment]
Also, without `Nuxt.js` we can not use constructions like that:
```js
this.app.$accessor.resetEmail()
```

like stated in the [docs](https://nuxt-typed-vuex.danielcroe.com/store/actions.html) for actions.

**Comment by danielroe** [comment]
@andrewvasilchuk I've added documentation for using as-is. However, I need to add the capability for us to extend the types for the store and therefore be able to access the accessor from within it.

**Comment by danielroe** [comment]
@andrewvasilchuk you'd be very welcome to test the current docs and support for using this library without Nuxt: `nuxt-typed-vuex@0.1.10-beta.2`. :smiley:

**Comment by andrewvasilchuk** [comment]
@danielroe , Sure, I will test it out on the big `Nuxt.js` project that has multiple nested and dynamic Vuex modules. Also on the weekends I will definitely include it in my `Vue CLI` project and also test it there.

**Comment by danielroe** [comment]
@andrewvasilchuk Thank you :blush:
