### ISSUE TITLE
fix: Using this module breaks Vue Chrome Extension

### ISSUE THREAD

**Issue by justinwaite** [danielroe/nuxt-typed-vuex#39]
**🐛 The bug**
When using this module, the Vuex part of the official Vue Chrome Extension does not work properly. The mutations all show up fine, but the state is never updated, and you are unable to mutate state in the extension.

**🛠️ To reproduce**
1. Open the Vue extension
2. Go to the Vuex tab
3. Observe that the resulting state from the last mutation does not match what the last mutation committed.
4. Try modifying the state using the extension – doesn't work (sometimes throws an error).

**🌈 Expected behaviour**
I would expect the Vue chrome extension to not be affected by this module.

**ℹ️ Additional context**
I'll try and get a sandbox going to demonstrate the issue, just don't have time right this minute.

**Comment by danielroe** [comment]
Thanks @justinwaite - much appreciate the report. I'll look into it, and if you do get that a chance I would appreciate that sandbox 🙂

**Comment by danielroe** [comment]
I can confirm the following:
1. Changing state within devtools does not lead to updating page until the devtools commit button is pressed (vs. not using `nuxt-typed-vuex`).
2. Occasionally an error message appears about mutating state if things are changed in the devtools.

@justinwaite This sounds like the same thing you are reporting in the issue. If you've experienced anything other than the above, please do let me know.

I imagine this could be to do with how the accessor's state and getters are created (namely, with `Object.defineProperty`). However, I'm not sure if this is an issue with devtools or `nuxt-typed-vuex`, and I've been experiencing broader issues with the devtools Vuex backend anyway, so will have to investigate further. Again, any further info would be appreciated.

**Comment by bjufre** [comment]
@danielroe any news on this??

**Comment by danielroe** [comment]
Although the presence of this module leads to the problem, I don't think it is in fact causing the issue, and it appears to be a bug with the devtools.

For example, when I change state within devtools the accessor doesn't update the page - but nor does the devtools appear to have actually updated the store, as a `console.log($vm0.$store.state.email)` doesn't show the updated state either.

Moreover, I don't see how the accessor could be causing this issue as it doesn't interact with the devtools at all, but directly with the store.

**Comment by ShaggyTech** [comment]
I was having a similar issue with the store state not getting updated in vue dev tools.  I managed to fix this by going to the Vue Dev Tools `Settings` and checking the box to enable `New Vuex Backend`.  After restarting the browser, vuex state is now working as designed.
