### ISSUE TITLE
fix: `$accessor` object does not contain mutations

### ISSUE THREAD

**Issue by SDVII** [danielroe/nuxt-typed-vuex#42]
**🐛 The bug**
The `$accessor` object contains state variables but no mutations

**🛠️ To reproduce**
1. Create a nuxt application and add some store variables with mutations.
2. Access the `$accessor` via middleware's context.

**🌈 Expected behavior**
Typescript recognizes store mutations.

**ℹ️ Additional context**

**Comment by SDVII** [comment]
To clarify, the mutations are working as expected in runtime. It's just that typescript doesn't recognize nor autocomplete them.

Awesome module btw, keep up the good work.

**Comment by danielroe** [comment]
@SDVII Thanks 🙂 How are you defining the missions mutations and the accessor type?

**Comment by SDVII** [comment]
The store:
```ts
import { MutationTree } from 'vuex/types/index';
import { getAccessorType } from 'nuxt-typed-vuex';

export const state = () => ({
  locales: [
    {
      code: 'en',
      name: 'EN',
    },
    {
      code: 'tr',
      name: 'TR',
    },
  ],
  locale: 'en',
});

export type RootState= ReturnType<typeof state>;

export const mutations: MutationTree<RootState> = {
  SET_LANG(state, locale: string) {
    if (state.locales.find(el => el.code === locale)) {
      state.locale = locale;
    }
};

export const accessorType = getAccessorType({
  state,
  mutations,
});

export const strict = false;
```
The types:
```ts
import { accessorType } from '~/store';

declare module 'vue/types/vue' {
  interface Vue {
    $accessor: typeof accessorType;
  }
}

declare module '@nuxt/types' {
  interface NuxtAppOptions {
    $accessor: typeof accessorType;
  }
}

```

**Comment by danielroe** [comment]
@SDVII The issue is that the type provided by vuex is interfering with type inference. (See note 1 [here](https://nuxt-typed-vuex.danielcroe.com/store/mutations.html).)

Just use a bare object, typing the state each time, or use my helper function which provides type info.

**Comment by SDVII** [comment]
Ah! sorry, I didn't notice that.
I just tried it out and it works perfectly now. Thanks a bunch!

**Comment by danielroe** [comment]
@SDVII Glad to help! Let me know if there's anything else I can do 🙃

**Comment by erwanjugand** [comment]
> @SDVII The issue is that the type provided by vuex is interfering with type inference. (See note 1 [here](https://nuxt-typed-vuex.danielcroe.com/store/mutations.html).)
> 
> Just use a bare object, typing the state each time, or use my helper function which provides type info. (Info at link.)

url has changed : https://typed-vuex.roe.dev/mutations 😀
