### ISSUE TITLE
docs: no info about nuxtServerInit()

### ISSUE THREAD

**Issue by webcoderkz** [danielroe/nuxt-typed-vuex#43]
There's no examples on how to use it with `nuxtServerInit()`, as i understood, we put it under `~/store/index.ts`:

```
export const actions = actionTree(
  { state },
  {
    async nuxtServerInit({ dispatch }) {
      await dispatch('submodule/actionName')
    }
  }
)
```

But it doesn't fire my action from a submodule, also i'm getting a type error: `Property 'dispatch' does not exist on type 'Pick<ActionContext<Required<NuxtStoreInput<() => { test: string; }, GetterTree<{ test: string; }, any>, MutationTree<{ test: string; }>, {}, {}>>>, "state" | "getters" | "commit" | "rootState" | "rootGetters">'.`

**Comment by danielroe** [comment]
@webcoderkz 

I think there are three issues here:
1. **Not firing your action**. Does it work if you don't use the `actionTree` helper?
2. **`dispatch` does not exist in context**. This was deliberate (although perhaps misguided?) given that [using `this.app.$accessor` to dispatch actions](https://nuxt-typed-vuex.danielcroe.com/store/actions.html) allows you to do so in a typed way instead. However, I think this is too opinionated and will revert it in the next release.
3. **Documentation**. Good spot! I'll add an example.

**Comment by danielroe** [comment]
@webcoderkz You should be able to access dispatch in the context, with `0.1.11`. And documentation is now updated.

Let me know if you need any help with your first issue (action not being fired). If so, could you provide a repro? I'll happily take a look.

**Comment by webcoderkz** [comment]
Thanks, would try it! I will reopen if i will have any issues.
