### ISSUE TITLE
docs: how do i user getters with params?

### ISSUE THREAD

**Issue by adrian-goe** [danielroe/nuxt-typed-vuex#61]
I want to get one element by ID from an array out of the store, so i dont have to filter them in the component. Is this possible?

**🔍 Where should you find it?**
[Docs Getters](https://nuxt-typed-vuex.danielcroe.com/store/getters.html)

**Comment by danielroe** [comment]
@adrian-goe It's worth saying that the answer will be the same for any method of defining a Vuex store (so will be equally relevant even if you are using `vuex-module-decorators`, for example).

1. The most performant approach is probably to transform your array to an object on load.
2. However, if you need to, you can export a getter that returns a function, e.g.:
   ```ts
   export const getters = getterTree(state, {
     getItemById: state => (id: number) => state.items.find(item => item.id === id)
   })
   ```
   **or**

   ```ts
   export const getters = {
     getItemById: (state: RootState) => (id: number) => state.items.find(item => item.id === id)
   }
   ```

**Comment by danielroe** [comment]
@adrian-goe Feel free to reopen if you have additional thoughts/questions. I appreciate your contribution 🙂
