### ISSUE TITLE
fix: Error: Cannot find module './utils'

### ISSUE THREAD

**Issue by andrewvasilchuk** [danielroe/nuxt-typed-vuex#65]
**🐛 The bug**
I am getting the following issue while running `npm run dev`:

![error](https://user-images.githubusercontent.com/44983823/70897484-6336a780-1ffb-11ea-8382-9d436df6f5cc.png)

**🛠️ To reproduce**
1. Install `nuxt-typed-vuex@0.1.15` , `@nuxt/typescript-build`, '@nuxt/typescript-runtime`
2. run `npm run dev`
3. See error in console

**🌈 Expected behaviour**
Project should boot up without the exception.

**ℹ️ Additional context**
Everything seems okay with `0.1.13`.

**Comment by danielroe** [comment]
Apologies, I should have updated docs. You will need to add `/typed-vuex/` to be transpiled.

**Comment by andrewvasilchuk** [comment]
@danielroe, Thanks!

**Comment by danielroe** [comment]
Thanks again for reporting :smiley:

**Comment by andrewvasilchuk** [comment]
@danielroe, Sorry, but that did not solve the issue.

**Comment by adrian-goe** [comment]
Hallo @danielroe  I have now the same issue with version  0.1.17
I have added `transpile: [/typed-vuex/,],`
I user `"nuxt": "2.11.0",` 
```

Error: Cannot find module './utils'
Require stack:
- node_modules/nuxt-typed-vuex/lib/index.js
- node_modules/@nuxt/core/dist/core.js
- node_modules/nuxt/dist/nuxt.js
- node_modules/@nuxtjs/hapi/lib/plugin.js
- server/index.js
at Object.<anonymous> (node_modules/nuxt-typed-vuex/lib/index.js:1)
```

**Comment by andrewvasilchuk** [comment]
@adrian-goe, These steps helped me: 

1. delete `node_modules`
2. `npm cache clean -f`
3. `npm install`

**Comment by adrian-goe** [comment]
Thanks, that worked @andrewvasilchuk
