### ISSUE TITLE
fix: Props couldn't use object alongside $accessor. Using array works

### ISSUE THREAD

**Issue by ram231** [danielroe/nuxt-typed-vuex#70]
**🐛 The bug**
What isn't working? Describe what the bug is.

I have a component that sends a simple Array/Object into its child component.
so that child component has a prop of Array/Object that needs to check its types.

```ts
export default Vue.extend({
  computed: {
    getDataFromStore() {
      return this.$accessor.getData(); // will throw error if props set to empty object
    },
  },
  async mounted() {
    try {
      await this.$accessor.fetchStore(); // will throw error if props set to empty object
    } catch (error) {
      this.$accessor.SET_ERROR(error) // will throw error if props set to empty object
    }
  },
  props:{} // doesn't work
 //prop:[] //it works
})
```

**🛠️ To reproduce**
1. Go to './store/index.ts'
2. Create a simple vuex state
3. call the getters and actions of the state
4.  add props to any component

**🌈 Expected behaviour**
~What did you expect to happen? Is there a section in the docs about this?~
I am able to send props to its child and alongside with having typed vuex
**ℹ️ Additional context**
~Add any other context about the problem here.~
I don't know what causes this error. I am not very familiar with Typescript's inferring types inside VSCODE.

**Comment by danielroe** [comment]
@ram321 This is a more general problem with `Vue.extend`. Within `mounted()` or other lifecycle  you won't be able to access quite a lot of the Vue instance properties.

So, for example, this won't work either:
```js
async mounted() {
    const a = this.getDataFromStore
},
```

You can get types for $accessor by specifying this manually:

```js
async mounted(this: Vue) {
  // type inference now works
}
```

If you find another solution, please do let me know and I'll update the docs.
