### ISSUE TITLE
fix: Deconstructing not existing object payload results in error.

### ISSUE THREAD

**Issue by tre-dev** [danielroe/nuxt-typed-vuex#72]
**🐛 The bug**

Deconstructing not existing object payload results in error.

`TypeError: Cannot read property 'someProperty' of undefined`

**🛠️ To reproduce**

```
export const actions = actionTree(
  {state, getters, mutations},
  {
    async someAction(
      {state, commit},
      {someProperty}: {someProperty?: string}
    ) {
       if (someProperty) // ... do something
    }
})

// in a component
this.$accessor.someAction() // results in error
this.$accessor.someAction({}) // works
```

**🌈 Expected behaviour**

There should ideally be no error if no object payload is given and the code is trying to deconstruct this not existing payload.

---

PS: Big thanks for the package. It's highly appreciated!

**Comment by danielroe** [comment]
@tre-dev Thanks - glad you like it 😊

In this case, you have declared a mandatory argument with an optional property. Try this instead:

```ts
async someAction(
{state, commit},
{someProperty}?: {someProperty?: string}
) {
if (someProperty) // ... do something
}
})
```
Hopefully that should declare an optional object with an optional property.

**Comment by tre-dev** [comment]
Thanks for the quick reply! Adding the `?` didn't work, typescript put out an error. However, this worked:

`{someProperty}: {someProperty?: string} = {}`

link: https://stackoverflow.com/questions/52843191/can-you-have-optional-destructured-arguments-in-a-typescript-function

**Comment by danielroe** [comment]
Yes, of course. Great!
