### ISSUE TITLE
docs: Property '$accessor' does not exist on type

### ISSUE THREAD

**Issue by JulianMar** [danielroe/nuxt-typed-vuex#73]
Hi, thanks for the very cool lib!

**📚 Is your documentation request related to a problem? Please describe.**
After adding the lib to my nuxt Project and creating a index.d.ts file I get this error  
`Property '$accessor' does not exist on type 'CombinedVueInstance<Vue, object, object, object, Record<never, any>>'`.  

Do I need to import this file somewhere? I have a vue-shim.d.ts aswell.

**🔍 Where should you find it?**
https://nuxt-typed-vuex.danielcroe.com/accessor/accessor.html#using-the-accessor

**ℹ️ Additional context**
TS: 3.75
Nuxt: 2.11.0

I use the vue composition api plugin aswell

**Comment by JulianMar** [comment]
Here is a little example
https://codesandbox.io/s/funny-easley-lqjc3?fontsize=14&hidenavigation=1&theme=dark

**Comment by danielroe** [comment]
@JulianMar I think you're getting that error because there is a problem defining a type somewhere in your app - probably in `index.d.ts` - but it's not related to `nuxt-typed-vuex`.

For example, having cloned your CodeSandbox, type inference is working for me.

Try commenting out other types in your `index.d.ts`, or let me see it in full, and I'll be happy to test.

**Comment by JulianMar** [comment]
I have a `vue-shim.d.ts` which includes 
```(ts)
declare module '*.vue' {
  import Vue from 'vue'
  export default Vue
}
```

do you think this could be the problem? 
If I remove it, I get the same error

**Comment by JulianMar** [comment]
found it. 
In my tsconfig I had this line
`"include": ["themes/**/*"]`
so index.d.ts was not included 

Thanks for you help

**Comment by danielroe** [comment]
@JulianMar Great - glad it's sorted :grinning:

**Comment by solangeDev** [comment]
I have the same problem 

import { defineComponent, computed, onMounted } from '@nuxtjs/composition-api'

export default defineComponent({
  name: 'IndexPage',
  layout: 'main',
  setup (_props, { root }) {
    const fields = [
      { key: 'id', label: '#' },
      { key: 'title', label: 'Titulo' },
      { key: 'description', label: 'Descripcion' },
      { key: 'actions', label: 'Acciones' }
    ]
    const items = computed(() => {
      return root.$accessor.posts
    })

    onMounted(() => {
    })

    return {
      items,
      fields
    }
  }
})
</script>

My error Property 'root' does not exist on type 'SetupContext<{}>'.Vetur(2339)
