### ISSUE TITLE
docs: Please add submodule usage example.

### ISSUE THREAD

**Issue by andrei-gheorghiu** [danielroe/nuxt-typed-vuex#90]
Trying to expand on this example: https://codesandbox.io/s/github/danielroe/nuxt-typed-vuex-example?from-embed

I even made sure my local deps are exactly the same as those in the codesandbox.

While everything seems to work, `this.$accessor.submodule` seems to be `undefined` at runtime. And that's because `submodule` is a property of `this.$accessor.modules`, not of `this.$accessor`.

Therefore, all the typing available @ `this.$accessor` is kind of useless, since it is cast at the wrong level.

Could you please update the example above with one method and one action in the submodule and a usage example in any component?

Thank you very much.

Your efforts are wildly appreciated (unrelated to this particular, petty request). Stay safe.

**Comment by michaelmarconi** [comment]
I'm struggling with this too.  I have defined a submodule and I can use the $accessor to get state and mutate that submodule (i.e. I get the results I expect in my web app), however my IDE (VS Code) is complaining that it doesn't understand the types on the submodule, e.g: 
```
Property 'xyz' does not exist on type 'MergedStoreType<typeof ...
```

I get no code completion for the submodule either.

I've verified that this works as expected with state in the root store, which it does.  It's just submodules, which is frustrating!

Otherwise, your project shows great promise and offers a much nicer solution than the others I've tried, so I'd love to get this working with submodules...

**Comment by danielroe** [comment]
@andrei-gheorghiu @michaelmarconi Thanks for the kind words!

For both of you, it would be great to see your code. Are you using Nuxt or vanilla Vue? I've just pushed an example to the example repo, namely:

```ts
  get firstName() {
    return this.$accessor.submodule.firstName
  }

  mounted() {
    setTimeout(() => {
      console.log('setting first name')
      this.$accessor.submodule.setFirstName('John')
    }, 500)
  }
```

The above works fine for me in vscode, including autocompletion, so it would be great to see an example project that isn't working so well.

**Comment by michaelmarconi** [comment]
I tried to fork your example project and make some changes but none of them would save.  I’ll try again later or see if I can find another way to demo the problem...

**Comment by michaelmarconi** [comment]
I forgot to mention that I’m using Nuxt.

**Comment by michaelmarconi** [comment]
Hi @danielroe — I'm using Nuxt.

I forked your code sandbox and tried the accessor on a submodule and it works perfectly, so I'm stumped.  See:  https://codesandbox.io/s/hopeful-lamport-60srs

I'll send you an email and see if we can find a way to solve this together.

**Comment by andrei-gheorghiu** [comment]
I don't remember what I was using. I was prototyping like mad, trying to decide on whether to use Nuxt or not (a bit overkill for that project), among other choices. Sandbox suggests I was in one of the Nuxt prototypes.

I'm excited to hear it works, I'll give it another go, first chance I get. Could the issue have been related to the typescript version used (under the hood)? More of a rhetorical question, really. 

I'll close this, since it obviously works as intended now.

Cheers!

**Comment by nperegrine** [comment]
Hello! I have a submodule in my app called "account".

I cannot access this submodule as @danielroe you mentioned as follows: 

`this.$accessor.account.getAccount` Does not work

The only way that seems to work is when I access the submodule from the "modules" object as follows:

`this.$accessor.modules.account.getAccount` Works for me

I am able to access the store and submodules when using the method above but I get the following error:

> Property 'account' does not exist on type '((options?: DispatchOptions | undefined) => any) | ((payload: any, options?: DispatchOptions | undefined) => any)'

Could this be a bug? I'm not sure if I'm missing something, please I need your help!

### // Here is my ~/store/index.ts file:

`import { getAccessorType, mutationTree } from "nuxt-typed-vuex";

import * as account from "~/store/modules/account";

export const state = () => ({
  payment_form_visible: false as boolean
});

export type RootState = ReturnType<typeof state>;

export const getters = {
  payment_form_visible: (state: RootState) => state.payment_form_visible
};

export const mutations = mutationTree(state, {
  TOGGLE_PAYMENT_FORM_VISIBILITY: state =>
    (state.payment_form_visible = !state.payment_form_visible)
});

// This compiles to nothing and only serves to return the correct type of the accessor
export const accessorType = getAccessorType({
  state,
  getters,
  mutations,
  modules: {
    account,
    transactions
  }
});
`

// Here is my ~/store/account module file

`import { getterTree, mutationTree, actionTree } from "nuxt-typed-vuex";
import Account from "~/models/Account";

export const state = () => ({
  account: {} as Account,
  loading: true as boolean
});

export type AccountState = ReturnType<typeof state>;

export const getters = getterTree(state, {
  getAccount: state => state.account,
  getLoading: state => state.loading
});

export const mutations = mutationTree(state, {
  SET_ACCOUNT: (state: AccountState, account: Account) =>
    (state.account = account),
  SET_LOADING_FALSE: state => (state.loading = false)
});

export const actions = actionTree(
  { state, getters },
  {
    async fetchAccount({ commit }, { id }) {
      try {
        const response = await this.$axios.$get(`/accounts/${id}`);

        commit("SET_ACCOUNT", response);
        commit("SET_LOADING_FALSE");
      } catch (e) {
        //
      }
    }
  }
);
`

### // This is my index.d.ts in my project root:

`import { accessorType } from "~/store";

declare module "vue/types/vue" {
  interface Vue {
    $accessor: typeof accessorType;
  }
}

declare module "@nuxt/types" {
  interface NuxtAppOptions {
    $accessor: typeof accessorType;
  }
}
`

### This is where I try to access the store using this.$accessor in my AccountCard.vue component:

` async mounted() {
    await this.$accessor.account.fetchAccount(); // does not work

    await this.$accessor.modules.account.fetchAccount(); // works but gives the error below:
  
  },`

I get the following error: 
> Property 'account' does not exist on type '((options?: DispatchOptions | undefined) => any) | ((payload: any, options?: DispatchOptions | undefined) => any)'

Please any help will be very appreciated!!!

**Comment by ryanmstokes** [comment]
Hi I have the exact same issue that @andrei-gheorghiu initially posted and nperegrine in the last comment.

I can only access the module by using .modules.nameOfModule but Typescript complains that modules does not exist. If I remove .modules the types are correct but thee path results in an error.

Spent a lot of time trying to figure this out :( Please help

Thank you!

**Comment by danielroe** [comment]
For Nuxt, if you create your submodules in a folder called modules, it will nest them in the `modules` namespace.

Try moving them out of the folder. Does that help?

**Comment by ryanmstokes** [comment]
Hi thanks danielroe for your quick reply, yes I realised that last night and it works without deeper nesting, I can live with that but it would be nice if you we could organise a store like:

├── store
│   ├── action-types.js
│   ├── index.js
│   ├── modules
│   │   ├── customer.js
│   │   ├── forms
│   │   │   ├── address.js
│   │   │   ├── contact.js
│   │   │   └── name.js
│   │   └── shipping-address.js
│   └── mutation-types.js

if there a way to achieve this currently?

Thanks again!

**Comment by ryanmstokes** [comment]
> Hello! I have a submodule in my app called "account".
> 
> I cannot access this submodule as @danielroe you mentioned as follows:
> 
> `this.$accessor.account.getAccount` Does not work
> 
> The only way that seems to work is when I access the submodule from the "modules" object as follows:
> 
> `this.$accessor.modules.account.getAccount` -> This works for me but generate the following typescript error:
> 
> > Property 'account' does not exist on type '((options?: DispatchOptions | undefined) => any) | ((payload: any, options?: DispatchOptions | undefined) => any)'
> 
> Could this be a bug? I'm not sure if I'm missing something, please I need your help!
> 
> ### // Here is my ~/store/index.ts file:
> ```
> import { getAccessorType, mutationTree } from "nuxt-typed-vuex";
> 
> import * as account from "~/store/modules/account";
> 
> export const state = () => ({
>   payment_form_visible: false as boolean
> });
> 
> export type RootState = ReturnType<typeof state>;
> 
> export const getters = {
>   payment_form_visible: (state: RootState) => state.payment_form_visible
> };
> 
> export const mutations = mutationTree(state, {
>   TOGGLE_PAYMENT_FORM_VISIBILITY: state =>
>     (state.payment_form_visible = !state.payment_form_visible)
> });
> 
> // This compiles to nothing and only serves to return the correct type of the accessor
> export const accessorType = getAccessorType({
>   state,
>   getters,
>   mutations,
>   modules: {
>     account,
>     transactions
>   }
> });
> ```
> 
> // Here is my ~/store/account module file
> 
> ```
> import { getterTree, mutationTree, actionTree } from "nuxt-typed-vuex";
> import Account from "~/models/Account";
> 
> export const state = () => ({
>   account: {} as Account,
>   loading: true as boolean
> });
> 
> export type AccountState = ReturnType<typeof state>;
> 
> export const getters = getterTree(state, {
>   getAccount: state => state.account,
>   getLoading: state => state.loading
> });
> 
> export const mutations = mutationTree(state, {
>   SET_ACCOUNT: (state: AccountState, account: Account) =>
>     (state.account = account),
>   SET_LOADING_FALSE: state => (state.loading = false)
> });
> 
> export const actions = actionTree(
>   { state, getters },
>   {
>     async fetchAccount({ commit }, { id }) {
>       try {
>         const response = await this.$axios.$get(`/accounts/${id}`);
> 
>         commit("SET_ACCOUNT", response);
>         commit("SET_LOADING_FALSE");
>       } catch (e) {
>         //
>       }
>     }
>   }
> );
> ```
> 
> ### // This is my index.d.ts in my project root:
> ```
> import { accessorType } from "~/store";
> 
> declare module "vue/types/vue" {
>   interface Vue {
>     $accessor: typeof accessorType;
>   }
> }
> 
> declare module "@nuxt/types" {
>   interface NuxtAppOptions {
>     $accessor: typeof accessorType;
>   }
> }`
> 
> ### This is where I try to access the store using this.$accessor in my AccountCard.vue component:
> 
> `async mounted() {
>     await this.$accessor.account.fetchAccount(); // does not work
> 
>     await this.$accessor.modules.account.fetchAccount(); // works but gives the error below:
>   
>   },
> ```
> 
> I get the following error:
> 
> > Property 'account' does not exist on type '((options?: DispatchOptions | undefined) => any) | ((payload: any, options?: DispatchOptions | undefined) => any)'
> 
> Please any help will be very appreciated!!!

I know this is old but for anyone dealing with this issue I believe the problem is that you cannot nest the submodule within a "modules" directory. The submodules should be at the top level of the store directory so "~/store/account" instead of "~/store/modules/account".
