### ISSUE TITLE
docs: How to use "this.app.$accessor" in getterTree ?

### ISSUE THREAD

**Issue by frck006** [danielroe/nuxt-typed-vuex#98]
**📚 Is your documentation request related to a problem? Please describe.**
A clear and concise description of what the problem is. Ex. I feel I should be able to [...] but I can't see how to do it from the docs.

**🔍 Where should you find it?**
What page of the docs do you expect this information to be found on?

**ℹ️ Additional context**
Add any other context or information.

**Comment by danielroe** [comment]
@frck006 Why are you looking to access the accessor through getters? Would love to know a bit about your use case.

**Comment by danielroe** [comment]
@frck006 The reason I ask is that Vuex expects getters to return a value - based solely upon store state and getters. (See [here](https://nuxt-typed-vuex.roe.dev/store/getters.html) and [here](https://vuex.vuejs.org/guide/getters.html).) You wouldn't expect to access actions or mutations from a getter.

**Comment by frck006** [comment]
@danielroe No, I don't want to have access to mutations or actions but a getter from another store.

@danielroe And now, I would like to have acces to **this.app** to get translate from i18n like **this.app.i18n.t(...)**

But perhaps, I do something not correctly.

**Comment by danielroe** [comment]
@frck006 You won't be able to access `this.app` in getters, at least not in vanilla Vuex. However, you can definitely access getters from another store, via the 4th argument. A getter receives four arguments: `localModuleState`, `localeModuleGetters`, `rootState`, and `rootGetters`.

However, you will need to manually type everything but the first one, unfortunately, as explained [in the docs](https://nuxt-typed-vuex.roe.dev/store/getters.html). You can do that manually based on the types that `typed-vuex` generates.

**Comment by frck006** [comment]
@danielroe Ok thank you for explanation.
